### PR TITLE
Added in boolean argparams to only show locked or unlocked images.

### PR DESCRIPTION
**Pull request by Grog4r**
This adds in two parameters for the base url `only_locked` and `only_unlocked`.
They can be used to only show the metadata for locked or unlocked images. They default to False.
Only one of them can be set to true.

### CODE REVIEW

**Review by Schwehn42 — COMMENTED** [review]
Why would the frontend want the locked resources? 
I thought the point is to only display images that are already available.  
Or do you want to display _all_ exisiting resources that aren't unlocked yet as grayed out?

**Comment by Grog4r** [comment]
I thought locked images would be displayed as Grayed out placeholders, that way you can know when to expect imagesAm 23.11.23, 10:48 schrieb Jakob Schwehn ***@***.***>:

   
  @Schwehn42 commented on this pull request. 
  Why would the frontend want the locked resources? I thought the point is to only display images that are already available. Or do you want to display all exisiting resources that aren't unlocked yet as grayed out?

**Comment by Schwehn42** [comment]
> I thought locked images would be displayed as Grayed out placeholders, that way you can know when to expect images

The way I interpreted the design I would probably only display the first locked item, otherwise the Feed would be cluttered

**Comment by Grog4r** [comment]
This is also fine by me.Am 23.11.23, 13:22 schrieb Jakob Schwehn ***@***.***>:

   
   
   I thought locked images would be displayed as Grayed out placeholders, that way you can know when to expect images 
   
  The way I interpreted the design I would probably only display the first locked item, otherwise the Feed would be cluttered

**Comment by Schwehn42** [comment]
> This is also fine by me

Okay, so instead, `GET /` could ignore any params and just return all available resource metas *plus* the next resource that will be available?

**Comment by Grog4r** [comment]
Should be done :+1:

**Pull request merged**
